plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.22'
}

version = "${mcversion}-${mod_version}-${tag_lanzador}"
group = "${author}.${modid}"
base {
    archivesName = "${mod_named}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        jvmArgument '-Xmx1G'
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'forge.enabledGameTestNamespaces', "${modid}"
    }

    server {
        systemProperty 'forge.enabledGameTestNamespaces', "${modid}"
        argument '--nogui'
    }

    clientData {
        arguments.addAll '--mod', "${modid}", '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

// Agregar src/generated/resources como fuente de recursos
sourceSets {
    main {
        resources {
            srcDir 'src/generated/resources'
        }
        java {
            exclude 'nadiendev/constructionwand/containers/handlers/HandlerPortableCell.java'
            exclude 'nadiendev/constructionwand/containers/handlers/HandlerWirelessTerminal.java'
            exclude 'nadiendev/constructionwand/containers/handlers/HandlerWirelessTerminalAE2WTLib.java'
            exclude 'nadiendev/constructionwand/containers/handlers/HandlerWirelessGrid.java'
            exclude 'src/generated/resources/.cache/*'
            exclude 'src/generated/resources/.cache'
        }
    }
}

repositories {
    mavenCentral()

    maven {
        url = "https://maven.su5ed.dev/releases"
    }

    maven {
        url = 'https://maven.creeperhost.net'
        content {
            includeGroup("com.refinedmods.refinedstorage")
        }
    }
    maven {
        url = "https://maven.blamejared.com"
    }
    maven {
        url = "https://maven.theillusivec4.top/"
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
    maven { url "https://maven.shedaniel.me" }
    maven {
        name = "Curse Maven"
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url = uri("https://modmaven.dev/")
        content {
            includeGroup "appeng"
            includeGroup "de.mari_023"
        }
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${neoversion}"

    //jei
    compileOnly "mezz.jei:jei-${mcversion}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${mcversion}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${mcversion}-neoforge:${jei_version}"

    // sophisticated backpacks
    compileOnly "curse.maven:sophisticatedbackpacks-422301:${sophisticatedbackpacks_version}"

    // sophisticated core
    compileOnly "curse.maven:sophisticatedcore-618298:${sophisticatedcore_version}"

    // Curios API
    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"
}

jar {
    manifest {
        attributes([
                "Specification-Title": archivesBaseName,
                "Specification-Vendor": "${author}",
                "Specification-Version": "1",
                "Implementation-Title": archivesBaseName,
                "Implementation-Version": "${version}",
                "Implementation-Vendor" :"${author}",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            mcversion              : mcversion,
            mod_version            : mod_version,
            modid                  : modid,
            author                 : author,
            mod_named              : mod_named,
            tag_lanzador           : tag_lanzador,
            description            : description,
            license                 : license,
            neoversion             : neoversion,
            loader_version        : loader_version,
            url                    : url,
            jei_version            : jei_version,
            sophisticatedbackpacks_version : sophisticatedbackpacks_version,
            sophisticatedcore_version : sophisticatedcore_version,
            curios_version             : curios_version,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.getRelease().set(21)
}