org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

# Mod Info
author=thetadev, SrNadien
modid=constructionwand
mod_named=ConstructionWandsRevived
mod_names=Construction Wands Revived
mod_description= Construction Wands make building easier! With a Construction Wand you can place multiple blocks (up to 1024) at once, extending your build on the side you're
facing. If that's not enough: you can upgrade your wand with additional cores, allowing you to place a block
behind the block you are facing, conjure blocks in mid air or destroy lots of blocks very fast.
This is my first minecraft mod. May the odds be ever in your favor.
licence=MIT License
mod_version=4.0.2
tag_lanzador=NeoForge

# Minecraft and NeoForge versions
mcversion=26.1.2
neo_version= 26.1.2.33-beta
minecraft_range_version=[26.1, 26.1.1]
neoforgeVersionRange=[26.1.0.8-beta,)
loader_version_range=[4,)

# NeoForge Parchment
neogradle.subsystems.parchment.minecraftVersion=1.21.11
neogradle.subsystems.parchment.mappingsVersion=2025.12.20
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Dependencies
jei_version=29.5.0.28
sophisticatedbackpacks_version=8007549
sophisticatedcore_version=8014105
ae2_version_id=8059221
guideme_version_id=7929350
refinedstorage_version_id=8117736
refinedstorage_curiosintegration_version_id=7999815
curios_version=15.0.0-beta.2+26.1.2