org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

author=thetadev, SrNadien
modid=constructionwand
mod_named=ConstructionWandsRevived
description=onstruction Wands make building easier!

With a Construction Wand you can place multiple blocks (up to 1024) at once, extending your build on the side you're
facing. If that's not enough: you can upgrade your wand with additional cores, allowing you to place a block
behind the block you are facing, conjure blocks in mid air or destroy lots of blocks very fast.

This is my first minecraft mod. May the odds be ever in your favor.
license=MIT


mcversion=1.21.8
neoversion=21.8.51
loader_version=[4,)
neogradle.subsystems.parchment.minecraftVersion=1.21.8
neogradle.subsystems.parchment.mappingsVersion=2025.07.20
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Source: https:# maven.blamejared.com/vazkii/botania/Botania/
botania=1.20.1-441-FORGE-SNAPSHOT
# Source: https:# maven.blamejared.com/mezz/jei/

#dependencies recipe viewers
jei_version=24.2.0.6

# Applied Energistics 2 (no disponible para 1.21.8)
ae2_version=NONE
guideme_version=21.8.4

# Refined Storage (no disponible para 1.21.8)
refinedstorage_version=NONE

# sophisticated backpacks
sophisticatedbackpacks_version=1.21.8-3.25.46.1735
sophisticatedcore_version=1.21.8-1.3.103.1365

# curios
curios_version=12.0.0+1.21.8

# ae2 wireless terminals (no disponible para 1.21.8)
ae2wtlib_version=NONE

# refined storage curios integration (no disponible para 1.21.8)
refinedstorage_curiosintegration_version_id=NONE

mod_version=4.0.0
# tag_version=Revived
tag_lanzador=NeoForge
